import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { VEHICLES, money } from '../lib/vehicles';
import Icon from '../components/Icon';

export default function Vehicles() {
  const [type, setType] = useState('All');
  const [max, setMax] = useState(100000);
  const [sort, setSort] = useState('featured');
  const [compare, setCompare] = useState([]);
  const dialog = useRef(null);
  const cars = VEHICLES.filter((car) => (type === 'All' || car.vehicle_type === type) && car.price_usd <= max).sort((a, b) => sort === 'price' ? a.price_usd - b.price_usd : sort === 'range' ? b.range_mi - a.range_mi : 0);
  const comparison = VEHICLES.filter((car) => compare.includes(car.id));
  const toggle = (id) => setCompare((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  return <div className="vehicles-page page-section">
    <div className="page-heading"><p className="eyebrow">THE AURION COLLECTION</p><h1>Find your forward<span className="accent">.</span></h1><p>Four electric vehicles. A world of possibility.<br />Find the one that feels like you.</p></div>
    <div className="catalog-controls"><div className="type-tabs" role="group" aria-label="Vehicle type">{['All', 'Sedan', 'SUV', 'Sports', 'Truck'].map((item) => <button key={item} className={type === item ? 'active' : ''} onClick={() => setType(item)} aria-pressed={type === item}>{item === 'All' ? 'All vehicles' : item === 'Sports' ? 'Grand tourer' : item}</button>)}</div><div className="catalog-options"><label>Budget<select value={max} onChange={(e) => setMax(Number(e.target.value))}><option value={100000}>Any price</option><option value={50000}>Under $50,000</option><option value={65000}>Under $65,000</option><option value={75000}>Under $75,000</option></select></label><label>Sort by<select value={sort} onChange={(e) => setSort(e.target.value)}><option value="featured">Featured</option><option value="price">Price: low to high</option><option value="range">Range: high to low</option></select></label></div></div>
    <p className="results-count" aria-live="polite">{cars.length} {cars.length === 1 ? 'vehicle' : 'vehicles'} to explore <span>All models are fully electric.</span></p>
    <div className="vehicle-grid">{cars.map((car) => <article className="vehicle-card" key={car.id}><div className="vehicle-image"><img src={car.picture_path} alt={`Aurion ${car.car_name} electric ${car.vehicle_type.toLowerCase()}`} loading="lazy" /><span className="vehicle-type">{car.vehicle_type === 'Sports' ? 'Grand tourer' : car.vehicle_type}</span><label className="compare-check"><input type="checkbox" checked={compare.includes(car.id)} onChange={() => toggle(car.id)} disabled={!compare.includes(car.id) && compare.length >= 3} />Compare {car.car_name}</label></div><div className="vehicle-body"><div className="vehicle-title"><h2>{car.car_name}</h2><span>From <strong>{money(car.price_usd)}</strong></span></div><p>{car.tagline}</p><div className="card-specs"><span><strong>{car.range_mi} mi</strong>Est. range</span><span><strong>{car.acceleration} s</strong>0–60 mph</span><span><strong>{car.seats}</strong>Seats</span></div><Link className="button outline full" to={`/vehicles/${car.id}`}>Explore & build <Icon name="arrow" size={18} /></Link></div></article>)}</div>
    {!cars.length && <div className="empty-state"><Icon name="globe" size={40} /><h2>A little more room to explore.</h2><p>No vehicles match these filters. Try a different budget or body style.</p><button className="button dark" onClick={() => { setType('All'); setMax(100000); }}>Reset filters</button></div>}
    <p className="fine-print">Concept pricing excludes taxes, delivery and fees. Range and performance are illustrative, not certified specifications.</p>
    {compare.length > 0 && <div className="compare-bar"><div><strong>{compare.length} of 3 selected</strong><span>{comparison.map((car) => car.car_name).join(' · ')}</span></div><button className="text-button" onClick={() => setCompare([])}>Clear</button><button className="button dark" disabled={compare.length < 2} onClick={() => dialog.current.showModal()}>Compare vehicles <Icon name="arrow" size={16} /></button></div>}
    <dialog ref={dialog} className="compare-dialog" aria-labelledby="compare-title"><div className="dialog-heading"><div><p className="eyebrow">SIDE BY SIDE</p><h2 id="compare-title">Your Aurion shortlist</h2></div><button className="icon-button" aria-label="Close comparison" onClick={() => dialog.current.close()}><Icon name="close" /></button></div><div className="comparison-scroll"><table><thead><tr><th scope="col">Model</th>{comparison.map((car) => <th key={car.id} scope="col"><img src={car.picture_path} alt="" /><strong>{car.car_name}</strong></th>)}</tr></thead><tbody>{[['Starting price', (car) => money(car.price_usd)], ['Body style', (car) => car.vehicle_type], ['Est. range', (car) => `${car.range_mi} mi`], ['0–60 mph', (car) => `${car.acceleration} s`], ['Seats', (car) => car.seats]].map(([label, value]) => <tr key={label}><th scope="row">{label}</th>{comparison.map((car) => <td key={car.id}>{value(car)}</td>)}</tr>)}<tr><th scope="row">Make it yours</th>{comparison.map((car) => <td key={car.id}><Link to={`/vehicles/${car.id}`} className="text-link" onClick={() => dialog.current.close()}>Build {car.car_name} <Icon size={16} /></Link></td>)}</tr></tbody></table></div></dialog>
  </div>;
}
